"""GitHub as a corpus source.

For a technical person with no X presence this is often the only place their
reasoning is written down in public, and the valuable part is not the repo
list. It is the argument in a review comment and the justification in a commit
message — technical reasoning under disagreement, which is exactly what the
synthesis is trying to reconstruct. So repo metadata is not read at all and
comments come first.

Three things learned from a live capture on 2026-08-03 shape everything here;
`github_contract.py` states them formally.

**Commit messages are mostly not available.** All 69 PushEvents in the capture
had no `commits` array — the payload is `{repository_id, push_id, ref, head,
before}` and nothing else, across both a huge repo and a small one. The
extraction and the wip/typo/merge filter are implemented and tested against the
documented shape, and `GitHubStats.push_events_without_commits` counts the
gap, so a run reports "69 pushes, 0 with messages attached" instead of quietly
producing nothing.

**A search result is not a document.** `search/issues?q=commenter:X` returns
the pull requests X commented on, and `item.body` is the *PR author's* text —
0 of 20 items in the capture were written by the subject. Ingesting those would
attribute twenty strangers' words to the target. The search is therefore used
only to find threads, and each thread's comments are fetched and filtered to
the ones the subject actually wrote.

**Coverage is recent, not historical.** `events/public` is capped at roughly
300 events and 90 days. The search path reaches further back — six months
versus three weeks in the capture — but only to threads the subject commented
in. Both limits are reported in the coverage block rather than left for a
reader to infer from a suspiciously short date range.
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from ..cache import Cache
from ..models import Document
from .base import SourceError, http_client, parse_date

API = "https://api.github.com"

# One page is 100 events and GitHub caps the feed at ~300, so three pages is
# the whole feed. Asking for a fourth spends a request to be told the same.
EVENT_PAGES = 3
EVENTS_PER_PAGE = 100

# Threads to open from the search result. Each is one core-API request, and the
# unauthenticated core allowance is 60/hour total — so the cap is much lower
# without a token, where 20 thread reads would be a third of the hourly budget
# spent on one target.
MAX_THREADS_AUTHENTICATED = 25
MAX_THREADS_ANONYMOUS = 8

# Commit messages that carry no reasoning. Matched against the subject line
# only: a commit whose *summary* is "fix typo" is noise even if some tool
# appended a sign-off, and a substantive commit that happens to contain the
# word "typo" in its body is not.
#
# Deliberately narrow. This filter is structural, like prefilter.py — it drops
# messages with no argument in them, never messages about a subject we would
# rather not read.
_NOISE_SUBJECTS = re.compile(
    r"""^(
        wip\b                       # wip, WIP: do not merge
      | fix(ing|ed)?\s+typos?\b
      | typos?\b
      | fix\s+whitespace\b
      | (minor\s+)?(formatting|format|lint|style)(\s+fix(es)?)?$
      | update\s+(readme|changelog)$
      | bump\s+version\b
      | \.$
    )""",
    re.IGNORECASE | re.VERBOSE,
)
# A merge commit's message is generated by git, not written by a person.
_MERGE_SUBJECT = re.compile(r"^merge\s+(branch|pull request|remote-tracking|tag)\b", re.IGNORECASE)

# Below this, a commit subject with no body is a label rather than a statement.
MIN_COMMIT_CHARS = 25


@dataclass
class GitHubStats:
    """What was read, what was skipped, and what the endpoints could not give.

    Every count here exists because its absence would be indistinguishable from
    a person who simply does not do that thing.
    """

    events_read: int = 0
    event_pages: int = 0
    review_comments: int = 0
    issue_comments: int = 0
    commits_kept: int = 0
    commits_filtered: int = 0
    filtered_by_reason: dict[str, int] = field(default_factory=dict)
    push_events: int = 0
    push_events_without_commits: int = 0
    threads_searched: int = 0
    threads_read: int = 0
    thread_comments_kept: int = 0
    thread_comments_by_others: int = 0
    search_total: int = 0
    authenticated: bool = False
    earliest: str = ""
    latest: str = ""
    notes: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "events_read": self.events_read,
            "event_pages": self.event_pages,
            "review_comments": self.review_comments,
            "issue_comments": self.issue_comments,
            "commits_kept": self.commits_kept,
            "commits_filtered": self.commits_filtered,
            "filtered_by_reason": dict(self.filtered_by_reason),
            "push_events": self.push_events,
            "push_events_without_commits": self.push_events_without_commits,
            "threads_searched": self.threads_searched,
            "threads_read": self.threads_read,
            "thread_comments_kept": self.thread_comments_kept,
            "thread_comments_by_others": self.thread_comments_by_others,
            "search_total": self.search_total,
            "authenticated": self.authenticated,
            "date_range": f"{self.earliest} to {self.latest}" if self.earliest else "",
            "notes": list(self.notes),
        }

    def summary_line(self) -> str:
        return (
            f"{self.review_comments} review comment(s), {self.issue_comments} issue "
            f"comment(s), {self.thread_comments_kept} from searched threads, "
            f"{self.commits_kept} commit message(s) "
            f"({self.commits_filtered} filtered as low-signal)"
        )


def classify_commit(message: str) -> str | None:
    """Why this commit message carries no reasoning, or None to keep it.

    Mirrors `prefilter.classify`: structural reasons only, returned as a name
    so the report can say what was dropped rather than only how much.
    """
    text = (message or "").strip()
    if not text:
        return "empty"
    subject = text.splitlines()[0].strip()
    if _MERGE_SUBJECT.match(subject):
        return "merge_commit"
    if _NOISE_SUBJECTS.match(subject):
        return "no_content"
    # A one-line commit needs to at least be a sentence; a commit with a body
    # has already shown someone had something to explain.
    if len(text.splitlines()) == 1 and len(subject) < MIN_COMMIT_CHARS:
        return "too_short"
    return None


def _headers() -> dict[str, str]:
    """Authenticated when a token is available, anonymous otherwise.

    Anonymous works and is the documented fallback; it is just 60 requests an
    hour against 5,000, which the caps above account for.
    """
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def is_authenticated() -> bool:
    return bool(os.environ.get("GITHUB_TOKEN", "").strip())


class _Reader:
    """Cached JSON GETs that never raise past the adapter."""

    def __init__(self, cache: Cache, log: Callable[[str], None]) -> None:
        self.cache = cache
        self.log = log
        self.requests = 0
        self.errors: list[str] = []
        self._client: Any = None

    def get(self, url: str) -> Any | None:
        cached = self.cache.get("github", url)
        if cached is not None:
            return cached
        if self.cache.offline:
            self.errors.append(f"--offline: {url} is not cached")
            return None
        try:
            if self._client is None:
                self._client = http_client()
            self.requests += 1
            resp = self._client.get(url, headers=_headers())
            if resp.status_code == 403 and "rate limit" in resp.text.lower():
                reset = resp.headers.get("x-ratelimit-reset", "")
                self.errors.append(
                    f"rate limited on {url}"
                    + (f"; resets at {_reset_time(reset)}" if reset else "")
                    + (
                        ""
                        if is_authenticated()
                        else ". Set GITHUB_TOKEN to raise 60/hr to 5,000/hr"
                    )
                )
                return None
            if resp.status_code == 404:
                self.errors.append(f"404 {url}")
                return None
            if resp.status_code >= 400:
                self.errors.append(f"{resp.status_code} {url}")
                return None
            payload = resp.json()
        except Exception as exc:  # transport, TLS, malformed JSON — all non-fatal
            self.errors.append(str(SourceError(f"fetching {url}: {exc}")))
            return None
        self.cache.put("github", url, payload)
        return payload

    def close(self) -> None:
        if self._client is not None:
            self._client.close()
            self._client = None


def _reset_time(raw: str) -> str:
    try:
        return datetime.fromtimestamp(int(raw), tz=timezone.utc).strftime("%H:%M UTC")
    except (TypeError, ValueError):
        return raw


def _document(
    *,
    source_id: str,
    url: str,
    author: str,
    published: Any,
    body: str,
    context: str | None,
    context_url: str | None,
    raw: dict[str, Any],
) -> Document:
    return Document(
        source="github",
        source_id=source_id,
        url=url,
        author_handle=author,
        published_at=parse_date(published),
        kind="reply" if context else "original",
        body=body.strip(),
        context=context,
        context_author=None,
        context_url=context_url,
        engagement={},
        outbound_links=[],
        part_count=1,
        raw=raw,
    )


def _is_subject(node: Any, login: str) -> bool:
    return isinstance(node, dict) and str(node.get("login", "")).lower() == login.lower()


class GitHubSource:
    """Reads one GitHub account's public writing. `target` is the login."""

    name = "github"

    def fetch(
        self,
        target: str,
        *,
        author_handle: str,
        cache: Cache,
        limit: int = 200,
        log: Callable[[str], None] = print,
    ) -> list[Document]:
        docs, _ = self.fetch_with_stats(
            target, author_handle=author_handle, cache=cache, limit=limit, log=log
        )
        return docs

    def fetch_with_stats(
        self,
        target: str,
        *,
        author_handle: str,
        cache: Cache,
        limit: int = 200,
        log: Callable[[str], None] = print,
        search_threads: bool = True,
    ) -> tuple[list[Document], GitHubStats]:
        login = target.strip().strip("/").lstrip("@").rsplit("/", 1)[-1]
        stats = GitHubStats(authenticated=is_authenticated())
        reader = _Reader(cache, log)
        docs: list[Document] = []
        try:
            docs.extend(self._from_events(login, author_handle, reader, stats, log))
            if search_threads and len(docs) < limit:
                docs.extend(self._from_search(login, author_handle, reader, stats, log))
        finally:
            reader.close()

        seen: set[str] = set()
        unique: list[Document] = []
        for doc in docs:
            if doc.source_id in seen:
                continue
            seen.add(doc.source_id)
            unique.append(doc)
        unique.sort(key=lambda d: d.published_at, reverse=True)
        unique = unique[:limit]

        if unique:
            stats.earliest = min(d.published_at for d in unique).strftime("%Y-%m-%d")
            stats.latest = max(d.published_at for d in unique).strftime("%Y-%m-%d")
        stats.notes.extend(reader.errors[:5])
        self._add_coverage_notes(stats)
        log(f"  github: {stats.summary_line()}")
        for note in stats.notes:
            log(f"    {note}")
        return unique, stats

    # -- events ---------------------------------------------------------

    def _from_events(
        self,
        login: str,
        author: str,
        reader: _Reader,
        stats: GitHubStats,
        log: Callable[[str], None],
    ) -> list[Document]:
        docs: list[Document] = []
        for page in range(1, EVENT_PAGES + 1):
            url = f"{API}/users/{login}/events/public?per_page={EVENTS_PER_PAGE}&page={page}"
            payload = reader.get(url)
            if not isinstance(payload, list):
                break
            stats.event_pages += 1
            stats.events_read += len(payload)
            for event in payload:
                if isinstance(event, dict):
                    docs.extend(self._from_event(event, login, author, stats))
            if len(payload) < EVENTS_PER_PAGE:
                break
        return docs

    def _from_event(
        self, event: dict[str, Any], login: str, author: str, stats: GitHubStats
    ) -> list[Document]:
        kind = event.get("type")
        payload = event.get("payload")
        if not isinstance(payload, dict):
            return []
        repo = (event.get("repo") or {}).get("name", "")

        # The actor is the account whose feed this is, and on all 16 comment
        # events in the capture `comment.user.login` equalled `actor.login`.
        # Both are checked anyway: the cost is one comparison and the failure it
        # prevents is attributing someone else's comment to the subject.
        if not _is_subject(event.get("actor"), login):
            return []

        if kind == "PullRequestReviewCommentEvent":
            return self._review_comment(payload, repo, login, author, stats)
        if kind == "IssueCommentEvent":
            return self._issue_comment(payload, repo, login, author, stats)
        if kind == "PushEvent":
            return self._push(payload, event, repo, author, stats)
        return []

    def _review_comment(
        self,
        payload: dict[str, Any],
        repo: str,
        login: str,
        author: str,
        stats: GitHubStats,
    ) -> list[Document]:
        comment = payload.get("comment")
        if not isinstance(comment, dict) or not _is_subject(comment.get("user"), login):
            return []
        body = str(comment.get("body") or "").strip()
        if not body:
            return []
        stats.review_comments += 1
        # The diff hunk is this document's `context`, and it is the same idea as
        # a reply's parent tweet: "keep a bitmap instead" is unreadable without
        # the code it is about.
        path = comment.get("path") or ""
        hunk = str(comment.get("diff_hunk") or "").strip()
        context = f"{path}\n{hunk}".strip() if (path or hunk) else None
        return [
            _document(
                source_id=f"gh-review-{comment.get('id')}",
                url=str(comment.get("html_url") or ""),
                author=author,
                published=comment.get("created_at"),
                body=body,
                context=context,
                context_url=str(comment.get("pull_request_url") or "") or None,
                raw={"kind": "review_comment", "repo": repo, "path": path},
            )
        ]

    def _issue_comment(
        self,
        payload: dict[str, Any],
        repo: str,
        login: str,
        author: str,
        stats: GitHubStats,
    ) -> list[Document]:
        comment = payload.get("comment")
        if not isinstance(comment, dict) or not _is_subject(comment.get("user"), login):
            return []
        body = str(comment.get("body") or "").strip()
        if not body:
            return []
        stats.issue_comments += 1
        raw_issue = payload.get("issue")
        issue: dict[str, Any] = raw_issue if isinstance(raw_issue, dict) else {}
        title = str(issue.get("title") or "")
        # The issue body is written by whoever opened the thread, so it is
        # context, never the subject's words. The title alone is enough to make
        # the comment legible and cannot be mistaken for a paragraph they wrote.
        context = f"{repo}: {title}" if title else None
        return [
            _document(
                source_id=f"gh-comment-{comment.get('id')}",
                url=str(comment.get("html_url") or ""),
                author=author,
                published=comment.get("created_at"),
                body=body,
                context=context,
                context_url=str(issue.get("html_url") or "") or None,
                raw={
                    "kind": "issue_comment",
                    "repo": repo,
                    "on_pull_request": "pull_request" in issue,
                },
            )
        ]

    def _push(
        self,
        payload: dict[str, Any],
        event: dict[str, Any],
        repo: str,
        author: str,
        stats: GitHubStats,
    ) -> list[Document]:
        stats.push_events += 1
        commits = payload.get("commits")
        if not isinstance(commits, list) or not commits:
            # The observed case, on 69 of 69 pushes. Counted rather than
            # ignored: "GitHub stopped sending commit messages" and "this
            # person pushed nothing" must not look the same in the report.
            stats.push_events_without_commits += 1
            return []
        docs: list[Document] = []
        for commit in commits:
            if not isinstance(commit, dict):
                continue
            message = str(commit.get("message") or "")
            reason = classify_commit(message)
            if reason is not None:
                stats.commits_filtered += 1
                stats.filtered_by_reason[reason] = stats.filtered_by_reason.get(reason, 0) + 1
                continue
            sha = str(commit.get("sha") or "")
            stats.commits_kept += 1
            docs.append(
                _document(
                    # The full sha, not an abbreviation. Document ids are the
                    # dedupe key, and a truncated one turns a collision into a
                    # silently dropped commit rather than a visible error.
                    source_id=f"gh-commit-{sha}",
                    url=f"https://github.com/{repo}/commit/{sha}" if repo and sha else "",
                    author=author,
                    # A commit has no timestamp inside the events payload; the
                    # push does. Close enough for cadence, and the alternative
                    # is one API call per commit.
                    published=event.get("created_at"),
                    body=message,
                    context=None,
                    context_url=None,
                    raw={"kind": "commit", "repo": repo, "sha": sha},
                )
            )
        return docs

    # -- search, then the threads it points at ----------------------------

    def _from_search(
        self,
        login: str,
        author: str,
        reader: _Reader,
        stats: GitHubStats,
        log: Callable[[str], None],
    ) -> list[Document]:
        """Reach past the events window, one search and N thread reads.

        Exactly one search request per run. The search API's limit is 30 per
        *minute* — an order of magnitude tighter than core — and paginating it
        would trade a strict limit for a marginal amount of extra coverage.
        """
        query = f"commenter:{login}+type:pr"
        payload = reader.get(f"{API}/search/issues?q={query}&per_page=30&sort=updated&order=desc")
        if not isinstance(payload, dict):
            return []
        items = payload.get("items")
        if not isinstance(items, list):
            return []
        stats.search_total = int(payload.get("total_count") or 0)
        stats.threads_searched = len(items)

        cap = MAX_THREADS_AUTHENTICATED if is_authenticated() else MAX_THREADS_ANONYMOUS
        docs: list[Document] = []
        for item in items[:cap]:
            if not isinstance(item, dict):
                continue
            comments_url = item.get("comments_url")
            if not isinstance(comments_url, str) or not comments_url.startswith(API):
                continue
            thread = reader.get(f"{comments_url}?per_page=100")
            if not isinstance(thread, list):
                continue
            stats.threads_read += 1
            title = str(item.get("title") or "")
            repo = str(item.get("repository_url") or "").rsplit("/repos/", 1)[-1]
            for comment in thread:
                if not isinstance(comment, dict):
                    continue
                # The filter that makes this endpoint safe. A thread contains
                # everyone's comments, and `search/issues` matched the thread,
                # not the author.
                if not _is_subject(comment.get("user"), login):
                    stats.thread_comments_by_others += 1
                    continue
                body = str(comment.get("body") or "").strip()
                if not body:
                    continue
                stats.thread_comments_kept += 1
                docs.append(
                    _document(
                        source_id=f"gh-comment-{comment.get('id')}",
                        url=str(comment.get("html_url") or ""),
                        author=author,
                        published=comment.get("created_at"),
                        body=body,
                        context=f"{repo}: {title}" if title else None,
                        context_url=str(item.get("html_url") or "") or None,
                        raw={"kind": "thread_comment", "repo": repo},
                    )
                )
        return docs

    # -- coverage ---------------------------------------------------------

    def _add_coverage_notes(self, stats: GitHubStats) -> None:
        """The two measured limits, stated wherever this corpus is read."""
        from .github_contract import EVENTS_MAX_EVENTS, EVENTS_WINDOW_DAYS

        if stats.event_pages:
            stats.notes.append(
                f"GitHub's events feed is capped at ~{EVENTS_MAX_EVENTS} events and "
                f"~{EVENTS_WINDOW_DAYS} days, so commits and comments found this way "
                "are recent activity, not history."
            )
        if stats.push_events and not stats.commits_kept:
            stats.notes.append(
                f"{stats.push_events} push event(s) carried no commit messages "
                f"({stats.push_events_without_commits} with no `commits` array at all). "
                "GitHub's events feed omitted them; this is not an absence of commits."
            )
        if stats.threads_searched:
            stats.notes.append(
                f"Searched {stats.threads_searched} of {stats.search_total} pull request(s) "
                f"this account commented on, and read {stats.threads_read}. The search API "
                "is limited to 30 requests per minute, separately from the core limit, so "
                "one search runs per target and is not paginated."
            )
        if not stats.authenticated:
            stats.notes.append(
                "Unauthenticated: 60 requests/hour, and thread reads are capped at "
                f"{MAX_THREADS_ANONYMOUS} because of it. Set GITHUB_TOKEN for 5,000/hour."
            )


def fetch_profile(login: str, cache: Cache, log: Callable[[str], None] = print) -> dict[str, Any]:
    """`GET /users/{login}`, for the identity signals discovery scores against."""
    reader = _Reader(cache, log)
    try:
        payload = reader.get(f"{API}/users/{login}")
    finally:
        reader.close()
    return payload if isinstance(payload, dict) else {}
