"""report.md -> HTML, for exactly the markdown render.py emits.

Not a general markdown engine, on purpose. The report is generated by our
own `render.py` from a known vocabulary — headers, bold, italics, inline
code, links, lists, blockquotes, fenced code, horizontal rules — and a
sixty-line converter over that vocabulary beats a dependency that would
also parse the constructs we never produce. The same reasoning that kept
beautifulsoup out of the source adapters keeps a markdown package out of
here. If render.py grows new syntax, this file is where it gets taught.

Everything is HTML-escaped before any markup is applied, so a document
title or body excerpt containing angle brackets renders as text.
"""

from __future__ import annotations

import html
import re

_CODE_SPAN = re.compile(r"`([^`]+)`")
_LINK = re.compile(r"\[([^\]]+)\]\((https?://[^)\s]+|#[^)\s]+)\)")
_BOLD = re.compile(r"\*\*(.+?)\*\*")
_ITALIC = re.compile(r"(?<![\w*])_([^_]+)_(?![\w*])")
_HEADER = re.compile(r"^(#{1,3})\s+(.*)$")


def _slug(text: str) -> str:
    """GitHub-style header anchors, matching the links render.py emits."""
    cleaned = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s]+", "-", cleaned.strip())


def _inline(text: str) -> str:
    escaped = html.escape(text, quote=False)
    escaped = _CODE_SPAN.sub(r"<code>\1</code>", escaped)
    escaped = _LINK.sub(r'<a href="\2">\1</a>', escaped)
    escaped = _BOLD.sub(r"<strong>\1</strong>", escaped)
    return _ITALIC.sub(r"<em>\1</em>", escaped)


def markdown_to_html(text: str) -> str:
    out: list[str] = []
    paragraph: list[str] = []
    quote: list[str] = []
    items: list[str] = []
    fence: list[str] | None = None

    def flush_paragraph() -> None:
        if paragraph:
            out.append(f"<p>{_inline(' '.join(paragraph))}</p>")
            paragraph.clear()

    def flush_quote() -> None:
        if quote:
            inner = "<br>".join(_inline(q) for q in quote)
            out.append(f"<blockquote>{inner}</blockquote>")
            quote.clear()

    def flush_items() -> None:
        if items:
            out.append("<ul>" + "".join(f"<li>{_inline(i)}</li>" for i in items) + "</ul>")
            items.clear()

    def flush_all() -> None:
        flush_paragraph()
        flush_quote()
        flush_items()

    for line in text.splitlines():
        if fence is not None:
            if line.strip().startswith("```"):
                out.append("<pre><code>" + html.escape("\n".join(fence)) + "</code></pre>")
                fence = None
            else:
                fence.append(line)
            continue
        stripped = line.strip()
        if stripped.startswith("```"):
            flush_all()
            fence = []
            continue
        header = _HEADER.match(stripped)
        if header:
            flush_all()
            level = len(header.group(1))
            title = header.group(2).strip()
            out.append(f'<h{level} id="{_slug(title)}">{_inline(title)}</h{level}>')
            continue
        if stripped in ("---", "***"):
            flush_all()
            out.append("<hr>")
            continue
        if stripped.startswith(">"):
            flush_paragraph()
            flush_items()
            quote.append(stripped[1:].lstrip())
            continue
        if stripped.startswith("- "):
            flush_paragraph()
            flush_quote()
            items.append(stripped[2:])
            continue
        if not stripped:
            flush_all()
            continue
        flush_quote()
        flush_items()
        paragraph.append(stripped)
    flush_all()
    if fence is not None:  # an unclosed fence still renders, as code
        out.append("<pre><code>" + html.escape("\n".join(fence)) + "</code></pre>")
    return "\n".join(out)
